---
- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  - name: install apache2 and update packages
    apt:
      name: apache2
      update_cache: yes
      state: present
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'       
  - name: install httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: restart apache
    service: 
      name: apache2 
      state: started 
      enabled: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: restart httpd
    service: 
      name: httpd 
      state: started 
      enabled: yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' 
    
 
